config/routes.rb
Rails.application.routes.draw do
  root "users#show"

  get '/users/:user_id/salons/:id/fav', to: 'users#fav'

  devise_for :users, path: 'auth', path_names:
    { sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register',
      sign_up: 'cmon_let_me_in' }

  resources :login, only: [:index]

  resources :users, only: [:show, :edit, :update] do
    resources :profile, only: [:show]
    resources :salons, only: [:index, :update]
  end

  resources :salons, only: [:new, :create, :show, :index, :edit, :update] do
    resources :services, only: [:new, :create, :show, :destroy]
    resources :products, only: [:new, :create, :show, :destroy]
    resources :stylistservice, only: [:new, :create, :destroy]
    resources :clientservices
  end
end

app/models/salon.rb
class Salon < ApplicationRecord
  belongs_to :owner
  has_many :services
  has_many :products
  has_many :salonusers
  has_many :users, through: :salonusers

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :phone, presence: true
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, uniqueness: true
  validates :owner_id, presence: true
  validate :belongs_to_owner

  mount_uploader :image, ImageUploader

  def belongs_to_owner
    creator = User.find(owner_id)
    if creator.user_type != "owner"
      errors.add(:owner, "must be the creator!")
    end
  end

  def owner
    User.find(owner_id)
  end

  def find_stylists(array)
    output = []
    array.each do |user|
      if user.user_type == "stylist"
        output << user
      end
    end
    output
  end

  def find_clients(array)
    output = []
    array.each do |user|
      if user.user_type == "client"
        output << user
      end
    end
    output
  end

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/salon_controller.rb
class SalonController < ApplicationController
  def new
    @salon = Salon.new
  end

  def create
    @salon = Salon.new(salon_params)
    @salon.user = current_user
    if @salon.save
      redirect_to root_path
      flash[:notice] = "Salon added successfully"
    else
      flash[:notice] = @location.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def salon_params
    params.require(:salon).permit(:name, :address, :city, :state, :zip_code, :neighborhood, :phone_number, :url, :user)
  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  def new
    @salon = Salon.new
  end

  def show
    @user = current_user
    @clientservice = Clientservice.new
    @salon = Salon.find(params[:id])
    @services = @salon.services
    @products = @salon.products
    @members = @salon.users
    @stylists = @salon.find_stylists(@members)
    @user_services = @user.services
    @clients = @salon.find_clients(@members)
    @is_owner = false
    if @user.id == @salon.owner_id
      @is_owner = true
    end
  end

  def create
    @salon = Salon.new(salon_params)
    @salon.owner_id = current_user.id
    if @salon.save
      redirect_to root_path
      flash[:notice] = "Salon added successfully"
    else
      flash[:notice] = @salon.errors.full_messages.join(", ")
      render :new
    end
  end

  def index
    @user = current_user
    @usersalons = @user.salons
    @salons = Salon.all.order('name ASC')
    if params[:search]
      @results = Salon.search(params[:search]).order('name ASC')
    else
      @salons = Salon.all.order('name ASC')
    end
    # respond_to do |format|
    #   format.html
    #   format.json { render json: @salons }
    # end
  end

  def edit
    @salon = Salon.find(params[:id])
    @user = current_user
    if @user.id != @salon.owner_id
      redirect_to root_path
    end
    @image = @salon.image
  end

  def update
    @salon = Salon.find(params[:id])
    @salon.update_attributes(salon_params)
    if !params[:salon][:image].nil?
      @salon.image = params[:salon][:image]
    end
    if @salon.save
      redirect_to root_path
    else
      render action: 'edit'
    end
  end

  private

  def salon_params
    params.require(:salon).permit(:name, :address, :city, :state, :zip_code, :neighborhood, :phone, :email, :owner, :open_chair_count)
  end
end

app/views/salons/_client.html.erb
<div class="row user-box">
  <div class="small-12 large-4 columns user-noshadow-box">
    <div class="row">
      <h1>services</h1>
    </div>
    <div class="row clients">
      <ul class="user-profiles">
      <% @services.each do |service| %>
      <li>
        <div
        class="large-5 columns  mini-profile" >
          <br />
          <i class="<%= service.icon %> fa-2x" aria-hidden="true"></i><br />
          <%= link_to service.name, salon_service_path(@salon.id, service.id) %><br />
          $<%= service.price %>
          est time: <%= service.time %><br />
        </div>
      </li>
      <% end %>
    </ul>
    </div>
    <%= link_to '+',  new_salon_clientservice_path(@salon.id, @clientservice), class:"button service-button add" %><br/>Request Appointment
  </div>

  <div class="small-12 large-4 columns user-noshadow-box">
    <div class="row">
      <h1>products</h1>
    </div>
    <div class="row">
      <ul class="user-profiles">
      <% @products.each do |product| %>
      <li>
        <div
        class="large-5 columns mini-profile" >
          <br />
          <i class="<%= product.icon %> fa-2x" aria-hidden="true"></i><br />
          <%= link_to product.name, salon_product_path(@salon.id, product.id) %><br />
          $<%= product.price %><br /><br />
          <%= product.description %>
        </div>
      </li>
      <% end %>
    </ul>
    </div>
  </div>

  <div class="small-12 large-4 columns user-noshadow-box">
    <div class="row">
      <h1>stylists</h1>
    </div>
    <div class="row">
      <ul class="user-profiles">
        <% @stylists.each do |stylist| %>
        <li>
          <div class="row">
            <div
            class="large-10 columns left mini-profile"
            style="background:
            linear-gradient(
              rgba(255, 255, 255, 0.5),
              rgba(255, 255, 255, 0.5)),
            <% if stylist.image.url != nil %>
              url(<%= stylist.image %>);
            <% else %>
              url(<%= stylist.default_image %>);
            <% end %>
            background-size: cover;
            background-position: center;" >
              <br />
              <% if stylist.image.url != nil %>
                <%= image_tag stylist.image.url, class:"mini-round-image" %><br />
              <% else %>
                <%= image_tag stylist.default_image, class:"mini-round-image" %><br />
              <% end %>
              <br />
              <%= link_to stylist.full_name, user_profile_path(@user.id, stylist.id), class:"button new-salon-button" %>
            </div>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>



<!-- </div> -->

app/views/salons/_edit_form.html.erb
<div class="row">
<%= form_for @salon, html: { multipart: true } do |q| %>
  <div class="small-12 large-6 columns">
    <div class="field login-field">
      <%= q.label :name, "Name" %>
      <%= q.text_field :name %>
    </div>

    <div class="field login-field">
      <%= q.label :address, "Address" %>
      <%= q.text_field :address %>
    </div>

    <div class="field login-field">
      <%= q.label :city, "City" %>
      <%= q.text_field :city %>
    </div>

    <div class="field login-field">
      <%= q.label :state, "State" %>
      <%= q.text_field :state %>
    </div>

    <div class="field login-field">
      <%= q.label :zip_code, "Zip Code" %>
      <%= q.text_field :zip_code %>
    </div>
  </div>

  <div class="small-12 large-6 columns">
    <div class="field login-field">
      <%= q.label :email %>
      <%= q.text_field :email %>
    </div>

    <div class="field login-field">
      <%= q.label :phone %>
      <%= q.text_field :phone %>
    </div>

    <div class="field login-field drop-down" id="user-type">
      <%= q.label :open_chair_count, "please enter number of chairs available" %>
      <%= q.text_field :open_chair_count %>
    </div>

    <div class="field">
      <%= q.label :image %><br>
      <%= q.file_field :image, id:"upload-here"%>
    </div>

    <!-- <div class="field login-field">
      <%= q.label :image %>
      <%= q.file_field :image, id:"upload-here"%>
    </div> -->

    <div class="actions">
      <a href="/" class="button new-salon-button"><</a>
      <input class="submit button new-salon-button"
        name="commit"
        type="submit"
        value="update location"
        id='uploader-button'/>
    </div>
  </div>
<% end %>
</div>

app/views/salons/_form.html.erb
<div class="row">
<%= form_for(@salon) do |q| %>
  <div class="small-12 large-6 columns">
    <div class="field login-field">
      <%= q.label :name, "Name" %>
      <%= q.text_field :name %>
    </div>

    <div class="field login-field">
      <%= q.label :address, "Address" %>
      <%= q.text_field :address %>
    </div>

    <div class="field login-field">
      <%= q.label :city, "City" %>
      <%= q.text_field :city %>
    </div>

    <div class="field login-field">
      <%= q.label :state, "State" %>
      <%= q.text_field :state %>
    </div>

    <div class="field login-field">
      <%= q.label :zip_code, "Zip Code" %>
      <%= q.text_field :zip_code %>
    </div>
  </div>

  <div class="small-12 large-6 columns">
    <div class="field login-field">
      <%= q.label :email %>
      <%= q.text_field :email %>
    </div>

    <div class="field login-field">
      <%= q.label :phone %>
      <%= q.text_field :phone %>
    </div>

    <!-- <div class="field login-field">
      <%= q.label :image %>
      <%= q.file_field :image, id:"upload-here"%>
    </div> -->

    <div class="actions">
      <a href="/" class="button login-page-button"><</a>
      <input class="submit button new-salon-button"
        name="commit"
        type="submit"
        value="add location" />
    </div>
  </div>
<% end %>
</div>

app/views/salons/_new_form.html.erb
<%= form_for(@salon) do |q| %>
  <div class="small-12 large-6 columns">
    <div class="field login-field">
      <%= q.label :name, "Name" %>
      <%= q.text_field :name %>
    </div>

    <div class="field login-field">
      <%= q.label :address, "Address" %>
      <%= q.text_field :address %>
    </div>

    <div class="field login-field">
      <%= q.label :city, "City" %>
      <%= q.text_field :city %>
    </div>

    <div class="field login-field">
      <%= q.label :state, "State" %>
      <%= q.text_field :state %>
    </div>

    <div class="field login-field">
      <%= q.label :zip_code, "Zip Code" %>
      <%= q.text_field :zip_code %>
    </div>
  </div>

  <div class="small-12 large-6 columns">
    <div class="field login-field">
      <%= q.label :email %>
      <%= q.text_field :email %>
    </div>

    <div class="field login-field">
      <%= q.label :phone %>
      <%= q.text_field :phone %>
    </div>

    <!-- <div class="field login-field">
      <%= q.label :image %>
      <%= q.file_field :image, id:"upload-here"%>
    </div> -->

    <div class="actions">
      <a href="/" class="button login-page-button"><</a>
      <input class="submit button new-salon-button"
        name="commit"
        type="submit"
        value="add location" />
    </div>
  </div>
<% end %>

app/views/salons/_owner.html.erb
<div class="row large-centered user-box">
  <div class="small-12 large-6 columns user-noshadow-box">
    <div class="row">
      <h1>services</h1>
    </div>
    <div class="row clients">
      <ul class="user-profiles">
      <% @services.each do |service| %>
      <li>
        <div
        class="small-11 large-5 columns mini-profile" >
          <br />
          <i class="<%= service.icon %> fa-2x" aria-hidden="true"></i><br />
          <%= link_to service.name, salon_service_path(@salon.id, service.id) %><br />
          $<%= service.price %><br />
          est time: <%= service.time %><br />
          <%= link_to 'Delete this service', salon_service_path(@salon.id, service.id), { method: :delete } %>
        </div>
      </li>
      <% end %>
    </ul>
    </div>
    <%= link_to 'add new service', new_salon_service_path(params[:id]), class:"button new-salon-button" %>

  </div>

  <div class="small-12 large-6 columns user-noshadow-box">
    <div class="row">
      <h1>products</h1>
    </div>
    <div class="row">
      <ul class="user-profiles">
      <% @products.each do |product| %>
      <li>
        <div
        class="small-11 large-5 columns mini-profile" >
          <br />
          <i class="<%= product.icon %> fa-2x" aria-hidden="true"></i><br />
          <%= link_to product.name, salon_product_path(@salon.id, product.id) %><br />
          $<%= product.price %><br /><br />
          <%= product.description %><br />
          <%= link_to 'Delete this product', salon_product_path(@salon.id, product.id), { method: :delete } %>
        </div>
      </li>
      <% end %>
    </ul>
    </div>
    <%= link_to 'add new product', new_salon_product_path(params[:id]), class:"button new-salon-button" %>
  </div>
</div>
<div class="row large-centered user-box">
  <div class="small-12 large-6 columns user-noshadow-box">
    <div class="row">
      <h1>stylists</h1>
    </div>
    <div class="row clients">
      <ul class="user-profiles">
        <% @stylists.each do |stylist| %>
        <li>
          <div
          class="small-11 large-5 columns left mini-profile"
          style="background:
          linear-gradient(
            rgba(255, 255, 255, 0.5),
            rgba(255, 255, 255, 0.5)),
          <% if stylist.image.url != nil %>
            url(<%= stylist.image %>);
          <% else %>
            url(<%= stylist.default_image %>);
          <% end %>
          background-size: cover;
          background-position: center;" >
            <br />
            <% if stylist.image.url != nil %>
              <%= image_tag stylist.image.url, class:"mini-round-image" %><br />
            <% else %>
              <%= image_tag stylist.default_image, class:"mini-round-image" %><br />
            <% end %>
            <br />
            <%= link_to stylist.full_name, user_profile_path(@user.id, stylist.id), class:"button mini-profile-button" %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="small-12 large-6 columns user-noshadow-box">
    <div class="row">
      <h1>clients</h1>
    </div>
    <div class="row">
      <ul class="user-profiles">
        <% @clients.each do |client| %>
        <li>
          <div
          class="small-11 large-3 columns left mini-profile"
          style="background:
          linear-gradient(
            rgba(255, 255, 255, 0.5),
            rgba(255, 255, 255, 0.5)),
          <% if client.image.url != nil %>
            url(<%= client.image %>);
          <% else %>
            url(<%= client.default_image %>);
          <% end %>
          background-size: cover;
          background-position: center;" >
            <br />
            <% if client.image.url != nil %>
              <%= image_tag client.image.url, class:"mini-round-image" %><br />
            <% else %>
              <%= image_tag client.default_image, class:"mini-round-image" %><br />
            <% end %>
            <br />
            <%= link_to client.full_name, user_profile_path(@user.id, client.id), class:"button mini-profile-button" %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/salons/_stylist.html.erb
<div class="row large-centered user-box">
  <div class="small-12 large-6 columns user-noshadow-box">
    <div class="row">
      <h1>services</h1>
    </div>
    <div class="row clients">
      <ul class="user-profiles">
      <% @services.each do |service| %>
      <li>
        <div
        class="large-3 columns left mini-profile" >
          <br />
          <i class="<%= service.icon %> fa-2x" aria-hidden="true"></i><br />
          <%= link_to service.name, salon_service_path(@salon.id, service.id) %><br />
          $<%= service.price %><br /><br />
          <% if @user_services.find_by(id: service.id).nil? %>
            <%= link_to '+',  new_salon_stylistservice_path(@salon.id, service.id), class:"button service-button add" %>
          <% else %>
            <%= link_to 'x',  salon_stylistservice_path(@salon.id, service.id), method: :delete, class:"button service-button" %>
          <% end %>
        </div>
      </li>
      <% end %>
    </ul>
    </div>
  </div>

  <div class="small-12 large-6 columns user-noshadow-box">
    <div class="row">
      <h1>clients</h1>
    </div>
    <div class="row">
      <ul class="user-profiles">
        <% @clients.each do |client| %>
        <li>
          <div
          class="large-3 columns left mini-profile"
          style="background:
          linear-gradient(
            rgba(255, 255, 255, 0.5),
            rgba(255, 255, 255, 0.5)),
          <% if client.image.url != nil %>
            url(<%= client.image %>);
          <% else %>
            url(<%= client.default_image %>);
          <% end %>
          background-size: cover;
          background-position: center;" >
            <br />
            <% if client.image.url != nil %>
              <%= image_tag client.image.url, class:"mini-round-image" %><br />
            <% else %>
              <%= image_tag client.default_image, class:"mini-round-image" %><br />
            <% end %>
            <br />
            <%= link_to client.full_name, user_profile_path(@user.id, client.id), class:"button mini-profile-button" %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="row large-centered user-box">
  <div class="small-12 large-12 columns user-noshadow-box">
    <div class="row">
      <h1>products</h1>
    </div>
    <div class="row">
      <ul class="user-profiles">
      <% @products.each do |product| %>
      <li>
        <div
        class="large-2 columns left mini-profile" >
          <br />
          <i class="<%= product.icon %> fa-2x" aria-hidden="true"></i><br />
          <%= link_to product.name, salon_product_path(@salon.id, product.id) %><br />
          $<%= product.price %><br /><br />
          <%= product.description %>
        </div>
      </li>
      <% end %>
    </ul>
    </div>
  </div>
</div>

app/views/salons/edit.html.erb
<div class="row ">
  <div class="small-12 large-8 large-centered medium-centered columns user-box">
    <div class="row">
      <h1>edit <%=@salon.name %></h1>
    </div>
    <div class="row">
      <% if @salon.image.url != nil %>
        <%= image_tag @image, id:"upload-image" %>
      <% end %>
      <%= render 'edit_form' %>
    </div>
  </div>
</div>

app/views/salons/index.html.erb
<div class="row small-12 large-6 large-centered user-box">
  <div class="small-12 large-12 columns user-noshadow-box">
    <div class="row">
      <h1><%= @user.full_name %>'s salons</h1>
    </div>
      <% @usersalons.each do |salon| %>
        <div class="row"
          id="salon-profile-<%=salon.id%>"
          style="background:
          linear-gradient(
            rgba(255, 255, 255, 0.8),
            rgba(255, 255, 255, 0.8)),
            <% if salon.image.url != nil %>
              url(<%= salon.image %>);
            <% end %>
          background-size: cover;
          background-position: center;">
          <a href="/salons/<%= salon.id %>">
            <div class="small-6 columns salon-info">
              <b><%= salon.name %></b><br />
              <%= salon.address %>, <%= salon.city %> <%= salon.state %><br />
              <%= salon.phone %><br />
              <%= salon.email %><br />
              </a>
              <% salon.services.each do |service| %>
                <i class="<%= service.icon %> mini-service-icon" aria-hidden="true"></i>
              <% end %>
              <br /><br />
            </div>
          </a>
        </div>

        <hr class="user-info-hr">
      <% end %>

      <div class="row">
        <h1>Find a new salon</h1>
      </div>
      <div class="">
        <%= form_tag(salons_path, :method => 'get') do %>
          <%= text_field_tag :search, params[:search], placeholder: 'search salons', class:"search-form" %>
          <%= submit_tag 'Search', name: nil, class:"search-button" %>
        <% end %>
      </div>
      <% if @results.nil? %>
          <div id="app"></div>
      <% else %>
        <div>
        <h3> Search Results: </h3>
        <% if @results.empty? %>
        <div class="row">
          <h3>
            Sorry, your search yielded no locations.
          </h3>
        </div>
        <% else %>
        <% @results.each do |salon| %>
          <div class="row"
            id="salon-profile-<%=salon.id%>"
            style="background:
            linear-gradient(
              rgba(255, 255, 255, 0.8),
              rgba(255, 255, 255, 0.8)),
              <% if salon.image.url != nil %>
                url(<%= salon.image %>);
              <% end %>
            background-size: cover;
            background-position: center;">
            <% if @user.is_stylist? %>
              <div class="small-6 columns salon-pic">
                <% if salon.open_chair_count != 0 %>
                  <hr class="user-info-hr">
                  <i class="fa fa-external-link open_chairs" aria-hidden="true"></i> <%= salon.open_chair_count %> chairs available<br /><br />
                  <hr class="user-info-hr">
                <% end %>
              </div>
            <% end %>
            <a href="/salons/<%= salon.id %>">
              <div class="small-6 columns salon-info">
                <b><%= salon.name %></b><br />
                <%= salon.address %>, <%= salon.city %> <%= salon.state %><br />
                <%= salon.phone %><br />
                <%= salon.email %><br />
                </a>
                <% salon.services.each do |service| %>
                  <i class="<%= service.icon %> mini-service-icon" aria-hidden="true"></i>
                <% end %>
                <br />
                <% if @user.is_client? && !salon.users.include?(@user)%>
                  <a href="/users/<%= @user.id %>/salons/<%= salon.id %>/fav" class="button favorite">+ add as favorite</a>
                <% end %>
              </div>
            </a>
          </div>
          <hr class="user-info-hr">
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/salons/new.html.erb
<div class="row ">
  <div class="small-12 large-8 large-centered medium-centered columns user-box">
    <div class="row">
      <h1>add new location</h1>
    </div>
    <div class="row">
      <%= render 'new_form' %>
    </div>
  </div>
</div>

app/views/salons/show.html.erb
<div class="row">
  <div class="small-12 large-12 large-centered medium-centered columns user-box">
    <div class="row">
      <h1><%=@salon.name %></h1>
    </div>
    <div class="row">
      <div class="small-4 columns salon-pic">
        <% if @salon.image.url != nil %>
          <%= image_tag @salon.image.url %>
        <% end %>
      </div>
        <div class="small-8 columns salon-info">
          <h3>
          address:<br>
          <b><%= @salon.address %>, <%= @salon.city %> <%= @salon.state %></b><br><br>
          phone:<br>
          <b><%= @salon.phone %></b><br><br>
          email:<br>
          <b><%= @salon.email %></b><br><br>
          </h3>
        </div>
    </div>
  </div>
</div>

<% if @user.user_type == "owner" && @is_owner %>
  <%= render 'owner' %>
<% elsif @user.user_type == "stylist" %>
  <%= render 'stylist' %>
<% else %>
  <%= render 'client' %>
<% end %>