config/routes.rb
Rails.application.routes.draw do
  root "users#show"

  get '/users/:user_id/salons/:id/fav', to: 'users#fav'

  devise_for :users, path: 'auth', path_names:
    { sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register',
      sign_up: 'cmon_let_me_in' }

  resources :login, only: [:index]

  resources :users, only: [:show, :edit, :update] do
    resources :profile, only: [:show]
    resources :salons, only: [:index, :update]
  end

  resources :salons, only: [:new, :create, :show, :index, :edit, :update] do
    resources :services, only: [:new, :create, :show, :destroy]
    resources :products, only: [:new, :create, :show, :destroy]
    resources :stylistservice, only: [:new, :create, :destroy]
    resources :clientservices
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :salonusers
  has_many :salons, through: :salonusers
  has_many :stylistservices
  has_many :services, through: :stylistservices

  mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, uniqueness: true

  def is_owner?
    user_type == "owner"
  end

  def is_stylist?
    user_type == "stylist"
  end

  def is_client?
    user_type == "client"
  end

  def full_name
    first_name + " " + last_name
  end

  def recent_salon
    salons.last
  end

  def default_image
    "https://s3.amazonaws.com/mirrorimages/uploads/user/image/default/stock-photo-curly-blonde-hair-closeup-wavy-blond-hair-background-close-up-texture-of-permed-hair-hairstyle-197410298.jpg"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @image = @user.image
    if @user != nil
      @status = @user.user_type
    end
    if @status == "owner"
      @owned_salons = []
      Salon.all.each do |salon|
        if salon.owner == @user
          @owned_salons << salon
        end
      end
    end
    if @status == 'stylist'
      @stylist_services = Stylistservice.where("user_id = #{@user.id}")
      @clients = []
      @client_appts = []
      Clientservice.all.each do |appt|
        if appt.stylist.id == @user.id
          @client_appts << appt
          unless @clients.include?(User.find(appt.user_id))
            @clients << User.find(appt.user_id)
          end
        end
      end
      @client_appts = @client_appts.sort_by { |appt| appt.datetime }
    end
    if @status == 'client'
      @client_appts = []
      Clientservice.all.each do |appt|
        if appt.user_id == @user.id
          @client_appts << appt
        end
      end
      @client_appts = @client_appts.sort_by { |appt| appt.datetime }
    end
  end

  def edit
    @user = current_user
    @image = @user.image
  end

  def update
    @user = current_user
    if params[:user].nil?
      redirect_to root_path
    else
      @user.image = params[:user][:image]
      if @user.save
        redirect_to root_path
        flash[:notice] = "Salon added successfully"
      else
        render :new
      end
    end
  end

  def fav
    @user = current_user
    @salon = Salon.find(params[:id])
    @salon.users << @user
    redirect_to salons_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :phone, :password)
  end
end

app/views/users/owner/_owner_management.html.erb
<div class="row">
  <h1>owner management console</h1>
</div>
  <% @owned_salons.each do |salon| %>
    <div class="row"
      id="salon-profile-<%=salon.id%>"
      style="background:
      linear-gradient(
        rgba(255, 255, 255, 0.8),
        rgba(255, 255, 255, 0.8)),
        <% if salon.image.url != nil %>
          url(<%= salon.image %>);
        <% end %>
      background-size: cover;
      background-position: center;">
      <div class="small-6 columns salon-pic">
        <% if salon.open_chair_count != 0 %>
          <hr class="user-info-hr">
          <i class="fa fa-external-link open_chairs" aria-hidden="true"></i> <%= salon.open_chair_count %> chairs available<br /><br />
          <%= link_to 'search for stylists', edit_salon_path(salon.id), class:"button new-salon-button" %>
          <hr class="user-info-hr">
        <% end %>
      </div>
      <a href="/salons/<%= salon.id %>">
        <div class="small-6 columns salon-info">
          <b><%= salon.name %></b><br />
          <%= salon.address %>, <%= salon.city %> <%= salon.state %><br />
          <%= salon.phone %><br />
          <%= salon.email %><br />
          </a>
          <% salon.services.each do |service| %>
            <i class="<%= service.icon %> mini-service-icon" aria-hidden="true"></i>
          <% end %>
          <br /><br />
          <%= link_to 'edit salon', edit_salon_path(salon.id), class:"button new-salon-button" %>
        </div>
      </a>
    </div>

    <hr class="user-info-hr">
  <% end %>
  <div class="row">
    <%= link_to '+ new location', new_salon_path, class:"button new-salon-button" %>
  </div>